### ISSUE TITLE
`install_locally.py` conflicts with standard development practices

### ISSUE THREAD

**Issue by robpkelly** [pyGSTio/pyGSTi#108]
[`install_locally.py`](/pyGSTio/pyGSTi/blob/master/install_locally.py) manually adds the path of the cloned repo to the python user site packages. This leads to some confusing behavior. If a user in a venv runs `install_locally.py` they will find that pyGSTi is not available in their venv, only in the root python environment (where pyGSTi's dependencies probably are not installed).

The README instructs developers to install pyGSTi as an egg, with `pip install -e .`. This is a better solution to the same problem. If this is done, manually adding the path only creates a confusing redundancy.

`install_locally.py` should be removed to avoid confusion from new users/developers.

**Comment by sserita** [comment]
Closed as this is now in 0.9.11 release
