### ISSUE TITLE
cvxopt issues on El Capitan

### ISSUE THREAD

**Issue by jarthurgross** [pyGSTio/pyGSTi#11]
Just wanted to document a problem that `cvxopt` seems to have with Macs running El Capitan. On running one of the tests, `test_bootstrap (__main__.TestDriversMethods)`, I get:

```python
ImportError: dlopen(~/anaconda/envs/py27/lib/python2.7/site-packages/cvxopt/lapack.so, 2): Symbol not found: _dgesv_
  Referenced from: ~/anaconda/envs/py27/lib/python2.7/site-packages/cvxopt/lapack.so
  Expected in: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
```

The issue cvxopt/cvxopt#45 documents what I think is the same problem, and it may be due to my use of anaconda. I'll try some fixes and see if I come up with a way to get it working.

**Comment by jarthurgross** [comment]
It appears that the issue was that I had installed `cvxopt` via `conda install cvxopt` instead of `pip install cvxopt`. Once I install with pip, all the `ImportError`s disappear. This should be mentioned in the documentation somewhere (especially since @kmrudin seems to have experienced similar issues with Enthought Canopy).

**Comment by Travis-S** [comment]
Is there some way to include these kinds of subtleties in the dependencies? As of ``devlop/c34ba68a590e5ad8d1adf7cf7ca840e246770c77``, ``requirements.txt`` doesn't list ``cvxopt`` as a dependency.

**Comment by jarthurgross** [comment]
`cvxopt` is a dependency of `cvxpy`, which is an optional dependency for pyGSTi (it's only used to compute the diamond-norm I believe), which I think is why it's not in `requirements.txt`. As far as including the subtlety of using `pip` versus `conda`, I don't know of a way. If it installs via `setup.py`, I believe any dependencies listed in there are installed using `pip`.

**Comment by LSaldyt** [comment]
Just for reference:

[Documentation](http://www.cvxpy.org/en/latest/install/) for `cvxpy` indicates that mixing pip and conda installs can cause errors (especially if `pip install --upgrade` is used when the package was originally installed with `conda`).   
In #6, the conda-installed version of `cvxopt` was preventing computing the diamond norm. Specifically, the version `1.8.1 py_35` needed to be updated to `1.8.1  py35_blas_openblas_203  [blas_openblas]  conda-forge` or downgraded to `1.7.1 py_35`. For me, the pip version worked as well.
