### ISSUE TITLE
Bug in jupyter_notebooks/Tutorials/objects/advanced/Instruments.ipynb

### ISSUE THREAD

**Issue by kmrudin** [pyGSTio/pyGSTi#111]
We do not add the intermediate measurement Iz to the germ list before LSGST is performed.  (The correct circuit list is still generated because Iz is added to the model.)  I think we should add after the line "germs = std.germs":

germs += [pygsti.objects.Circuit(('Iz',))]

**Comment by robpkelly** [comment]
Hey, was this issue ever resolved?

**Comment by enielse** [comment]
Fixed by 19c0ed47c1e576a37dba183484c529b9d2d42788.

**Comment by enielse** [comment]
Version 0.9.10 contains the fix for this issue.
