### ISSUE TITLE
pyGSTi default install won't import (Win10)

### ISSUE THREAD

**Issue by drewrisinger** [pyGSTio/pyGSTi#125]
**Describe the bug**
A default installation of pyGSTi (from Git) doesn't seem to import correctly.

**To Reproduce**
1. Clone pygsti
2. Checkout 6d0722d6: ``git checkout 6d0722d6`` (probably also develop branch, 2 commits behind)
3. ``pip install -e .``
4. ``python -c "import pygsti"``

**Expected behavior**
No errors/messages to be thrown

**Error messages:**
(**Note**: below code was run through Jupyter, so exact traceback may vary.)
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
...\pygsti\pygsti\objects\profiler.py in 
     18 try:
---> 19     import psutil as _psutil
     20 

ModuleNotFoundError: No module named 'psutil'

During handling of the above exception, another exception occurred:

ModuleNotFoundError                       Traceback (most recent call last)
test_script.py in 
      6 
      7 import numpy as np
----> 8 import pygsti, cirq
      9 
      10 circuit_dir = "umd-demo-circuits-4-30-2020"

...\pygsti\pygsti\__init__.py in 
     13 from ._version import __version__
     14 
---> 15 from . import algorithms as alg
     16 from . import construction as cst
     17 from . import objects as obj

...\pygsti\pygsti\algorithms\__init__.py in 
     12 # the package namespace
     13 
---> 14 from .core import *
     15 from .grammatrix import *
     16 from .germselection import *

...\pygsti\pygsti\algorithms\core.py in 
     16 import time as _time
     17 
---> 18 from .. import optimize as _opt
     19 from .. import tools as _tools
     20 from .. import objects as _objs

...\pygsti\pygsti\optimize\__init__.py in 
     12 # the package namespace
     13 from .optimize import *
---> 14 from .customlm import *

...\pygsti\pygsti\optimize\customlm.py in 
     15 #from scipy.optimize import OptimizeResult as _optResult
     16 
---> 17 from ..tools import mpitools as _mpit
     18 from ..objects.verbosityprinter import VerbosityPrinter as _VerbosityPrinter
     19 

...\pygsti\pygsti\tools\__init__.py in 
     11 #Import the most important/useful routines of each module into
     12 # the package namespace
---> 13 from .jamiolkowski import *
     14 from .listtools import *
     15 from .matrixtools import *

...\pygsti\pygsti\tools\jamiolkowski.py in 
     10 
     11 import numpy as _np
---> 12 from ..objects.basis import Basis as _Basis
     13 from . import basistools as _bt
     14 from . import matrixtools as _mt

...\pygsti\pygsti\objects\__init__.py in 
     64 from .opfactory import EmbeddingOpFactory
     65 
---> 66 from .model import Model
     67 from .explicitmodel import ExplicitOpModel
     68 from .explicitmodel import ExplicitOpModel as GateSet  # alias

...\pygsti\pygsti\objects\model.py in 
     22 from ..tools import optools as _gt
     23 from ..tools import slicetools as _slct
---> 24 from ..tools import likelihoodfns as _lf
     25 from ..tools import jamiolkowski as _jt
     26 from ..tools import basistools as _bt

...\pygsti\pygsti\tools\likelihoodfns.py in 
     21 from . import mpitools as _mpit
     22 from . import slicetools as _slct
---> 23 from ..objects import objectivefns as _objfns
     24 from ..objects.smartcache import smart_cached
     25 

...\pygsti\pygsti\objects\objectivefns.py in 
     17 from .. import optimize as _opt, tools as _tools
     18 from ..tools import slicetools as _slct, mpitools as _mpit
---> 19 from . import profiler as _profiler
     20 from .computationcache import ComputationCache as _ComputationCache
     21 from .bulkcircuitlist import BulkCircuitList as _BulkCircuitList

...\pygsti\pygsti\objects\profiler.py in 
     25 except ImportError:
     26     import sys as _sys
---> 27     import resource as _resource
     28 
     29     def _get_mem_usage():

ModuleNotFoundError: No module named 'resource'
```

**Environment (please complete the following information):**
 - pyGSTi version: ``develop`` (commit 6d0722d6)
 - python version: 3.7
 - OS: Windows 10

**Comment by drewrisinger** [comment]
I resolved this locally by ``pip install psutil``

**Comment by robpkelly** [comment]
Strange, I can't seem to reproduce this on python 3.7.7.

@drewrisinger what python version are you using exactly? (i.e. with `python --version`)

**Comment by drewrisinger** [comment]
python 3.7.6 in a clean conda environment.

**Comment by drewrisinger** [comment]
That is strange, I mostly meant it as an FYI for future release. It has an obvious workaround, so not a hangup for me.

**Comment by robpkelly** [comment]
Oh, this is bizarre! Apparently `resource` is a [Unix-specific builtin](https://docs.python.org/3.8/library/unix.html) and is not available on Windows. I had no idea.

**Comment by robpkelly** [comment]
@enielse which of the following do you favor:
1. Make `psutil` a required dependency
2. Disable memory profiling on Windows when `psutil` is not installed
3. Write a custom solution for WIndows when `psutil` is not installed

**Comment by enielse** [comment]
The absence of `psutil` on windows is a known possibility, and the code it looks, from the traceback that the try/except block in `profiler.py` is correctly trying to use a fallback implementation that doesn't requires `psutil`.  The real error appears to be that **`resource` is not found**, which pyGSTi assumes is a built-in module that is always present, and is required by the fallback.

I think it used to be that python shipped with `resource`, but perhaps in newer versions it's been done away with?  If so, maybe it's been replaced with something we can use instead.  In any case, thanks for the heads up on this.

**Comment by robpkelly** [comment]
@enielse Python ships with `resource` on Unix platforms (including OS X and linux) but not on Windows, and that seems to be what's causing our issue. `psutil` itself would be the platform-agnostic solution to this problem, but then we'd want to make it required.

**Comment by robpkelly** [comment]
@drewrisinger If you get a chance, can you confirm that #131 resolves this issue? We don't have a windows environment on hand at the moment.

**Comment by enielse** [comment]
Reopening since this fix isn't in a final release yet.  Tagging it as such.

**Comment by drewrisinger** [comment]
I commented on #131 but repeating here: #131 worked on my local machine, so I view this issue as resolved. Thanks!

**Comment by enielse** [comment]
Version 0.9.10 fixes this issue.
