### ISSUE TITLE
Pip installation of pyGSTi and everything else except mpi4py

### ISSUE THREAD

**Issue by kmrudin** [pyGSTio/pyGSTi#126]
Can we add a pip install option that installs _all_ optional dependencies _except_ mpi4py?  There are some environments in which building mpi4py is rather difficult.  It would be nice to be able to still install all other optional dependencies in one fell swoop with something like

pip install -e . [complete-less-mpi4py]

(Or, for the PyPI version - pip install pygsti[complete-less-mpi4py])

Thanks!

**Comment by robpkelly** [comment]
Certainly!

I'm surprised to find that there is no `pip` option for blacklisting requirements by name. Looks like there's been at least one request to do so that's fallen through (see pypa/pip#3090). Absent that, we might as well just add a target for a common case like this.
