### ISSUE TITLE
Importing fails on Windows 10 - cannot import 'bulk_eval_compact_polynomials_complex'

### ISSUE THREAD

**Issue by enielse** [pyGSTio/pyGSTi#141]
There is potential problem on Windows 10 builds resulting in `import pygsti` (using the current development version, but this probably applies to v0.9.9.2 as well) raising:

`ImportError: cannot import name 'bulk_eval_compact_polynomials_complex' from 'pygsti.objects.opcalc'`.

This seems to occur when building the C-extensions fails (while running setup.py) *but* when the `.pyd` (windows dll) output file such as `.../pygsti/objects/opcalc/fastopcalc.*.pyd` is still created.  The created file is "half-baked", and does not contain all the requisite symbols, causing the import error above.  That is, because the C-extension file exists, pygsti tries to import it, but this import fails because the file resulted from a failed compilation.

Maybe we can fix this issue by ensuring that all *.pyd files are removed when handling a failed C-extension compilation in setup.py? (maybe we should similarly remove *.so files on linux and Mac builds?)  

**A temporary fix** for users experiencing this error is to either:
1. manually remove the bad *.pyd files so pygsti falls back to its pure python implementations.
2. update/fix the c++ compiling environment so that compilation doesn't fail.  After the .pyd files are removed, running `pip install -e .` from the root `pyGSTi` directory will attempt to rebuild the extensions.

**Comment by sserita** [comment]
I ran into a related problem on Mac where I had a Cython-enabled local install (i.e. `pip install -e .[complete]`) from `master` branch and then switched to the `beta` branch. I think there was some mismatch between the definitions in `pygsti.objects.opcalc` between the branches, but the Cython was not automatically recompiled - I hit exactly the same import error.

Not exactly sure how the dependencies are managed for Cython, but would definitely be in favor of cleaning the compiled files when errors or changes in the Python interface are detected.

**Comment by enielse** [comment]
Hopefully the introduction of wheels in version 0.9.10 will remedy this problem.  Closing this issue.
