### ISSUE TITLE
Tutorials on implementing new GST models

### ISSUE THREAD

**Issue by SchineCompton** [pyGSTio/pyGSTi#177]
**Is your feature request related to a problem? Please describe.**
We are an experimental team, and we would like to do gate set tomography on our 4 level qudit system. Is there a tutorial or reference on how to implement a new GST model? I had a look around and couldn't find one in the document. Alternatively, can I have some hint where to start reading the code? The code seems to be very well engineered and a bit difficult to find where to get started with.

**Describe the solution you'd like**
A tutorial on how to create a new GST model for custom quantum systems (for example qutrit or qudit), as well as a custom non-standard gate set.

**Describe alternatives you've considered**
If I can have some hint on where to get started, I can try to contribute this tutorial.

**Comment by enielse** [comment]
This is a great suggestion, and we'll try to get a tutorial out on this in the near future.  The recently released 0.9.10 is still lacking in this area: models are now created most easily from `ProcessorSpec`, but currently there's just a `QubitProcessorSpec` and not a `QuditProcessorSpec`, which would be a natural addition.  I expect that we'll add this functionality soon and at this point create a tutorial on it.  In the meantime, taking a look at the [qutrit example notebook](https://github.com/pyGSTio/pyGSTi/blob/master/jupyter_notebooks/Examples/QutritGST.ipynb) might be the most helpful.

**Comment by enielse** [comment]
Closing now that version 0.9.10.1 is released.
