### ISSUE TITLE
RB package - code overlap?

### ISSUE THREAD

**Issue by Travis-S** [pyGSTio/pyGSTi#18]
In reviewing recent updates to the RB tutorial on `develop`, I noticed there appears to be some code duplication between `rbresults.py` and `rbobjs.py`. `rbobjs` contains the `RBResults` object, which is also present in `rbresults`. Given the commit history, I'm assuming `rbobjs` is meant to supercede `rbresults`. (`rbresults` was last worked on in commit 9689a748dd8 on 10/6, while `robjs` came into existence as part of the refactor in commit 025bf1b8a704f on 10/10.)

If this is indeed the case, I would propose we delete `rbresults`.

**Comment by enielse** [comment]
Yes, rbresults.py should have been removed as it was replaced by rbobjs.py  -- now it is.
