### ISSUE TITLE
Allow bounds on parameters in GST optimizer

### ISSUE THREAD

**Issue by kevincyoung** [pyGSTio/pyGSTi#183]
Models containing interpolated gates are only defined for a finite range of parameters. I'd like to be able to fit these models using GST.

It would be very helpful if the GST optimizer could accept hard bounds (or inequality constraints) on the parameters. 

Alternatives include changing the interpolated gates to behave in some controlled manner outside of their bounding boxes, and then double checking that the optimizer hasn't converged on an infeasible point.

**Comment by enielse** [comment]
This functionality has been added in version 0.9.10, and can be accessed by setting the `parameter_bounds` attribute of model members (e.g. gate objects).
