### ISSUE TITLE
Read-in failures with empty counts.

### ISSUE THREAD

**Issue by tjproct** [pyGSTio/pyGSTi#188]
There are various read-in problems when a .txt dataset contains circuits with no counts, specified either by (1) an empty space where the data should be or (2) "BAD".

This is on develop.

Code attached.

[readin-bug.zip](https://github.com/pyGSTio/pyGSTi/files/6611184/readin-bug.zip)

**Comment by enielse** [comment]
This has been fixed in version 0.9.10.
