### ISSUE TITLE
mpi4py required to run model's probabilities method

### ISSUE THREAD

**Issue by kmrudin** [pyGSTio/pyGSTi#189]
If you do not have mpi4py installed, the following will fail:

`import pygsti`
`from pygsti.modelpacks import smq1Q_XYI`
`target_model = smq1Q_XYI.target_model()`
`target_model.probabilities(())`

The traceback yields `ModuleNotFoundError: No module named 'mpi4py'` from line 254 in pyGSTi/pygsti/objects/distlayout.py.  The quick solution is to comment out line 254, but this disables mpi4py support for those who are using it.  A better solution would be to gracefully skip the import statement if mpi4py is not available, though there may be a solution superior to that as well.

**Comment by enielse** [comment]
Version 0.9.10 contains the fix for this issue.
