### ISSUE TITLE
RB Results Object Plotting - Error Handling

### ISSUE THREAD

**Issue by Travis-S** [pyGSTio/pyGSTi#19]
At the end of Tutorial 16, we demonstrate fitting different-order RB models. I noticed some issues related to the error-handling based on different combinations of the input parameters.

Currently, after instantiating the figure and extracting some variables, we check how `gstyp` and `analytic_params` play with `analytic` around line 413:

```python
if analytic != None:
   if gstyp != 'clifford':
        print("Analytical curve is for Clifford decay!")            
   if analytic_params==None:
      print("Function must be given the analytical parameters!")
    f_an = analytic_params['f']
```

This code snippet raises two questions:

* If `gystp` is not "clifford" (i.e., is "primitive") then does it make sense to plot the analytic decay curve? If not, maybe a warning which indicates this discrepancy occurred, and sets `analytic = None` would be a good solution:

```python
if gstyp != 'clifford':
    print("Analytical curve is for Clifford decay only. Setting analytic to None.")
    analytic = None  
```
  
* Just after this code snippet, we attempt to extract out the analytic parameters from the `analytic_params` dictionary. However, the original snippet doesn't raise any kind of error when `analytic != None`, but `analytic_params = None`. It is true that the very next line which executes (`f_an = analytic_params['f']`) will raise an error, since `analytic_params` is None, but it's not a very helpful error:

```python
TypeError: 'NoneType' object has no attribute '__getitem__'
```

As such, I'd like to propose adding the following code (or some variant thereof) on line 399 to do this check before we start making the plot:

```python
if (analytic is not None) and (gstyp != 'clifford'):
    print("Analytical curve is for Clifford decay only. Setting analytic to None.")
    analytic = None  
if (analytic is not None) and (analytic_params is None):
    raise ValueError, "No input analytic parameters specified.\
 Please specify analytic_params, or set analytic to None."
```

This would help us resolve some potential contradictions between the input parameters before running the rest of the function.

**Comment by tjproct** [comment]
Suggested change implemented.
