### ISSUE TITLE
RB Results Object Plotting - plot aesthetics

### ISSUE THREAD

**Issue by Travis-S** [pyGSTio/pyGSTi#20]
A few thoughts regarding the aesthetics of the RB plots:

* Could we display the legend by default? I was a bit confused when the legend didn't show up.

* The original color scheme was developed to ensure good contrast between the data (dots) and the fit (line). Now that there are two possible fits, as well as the possibility that all three (data, zeroth order, and first order) could be displayed on the same plot, I'd like to suggest we use a [triadic color scheme](http://www.tigercolor.com/color-lab/color-theory/color-theory-intro.htm#triadic) to help ensure that maximum contrast between the colors when ``order`` is set to `'all'`. To help preserve contrast when we plot either the first or zeroth order fit and the data, I'd recommend the following colors:
    * Data: Keep at `cmap(30)`
    * Zeroth order fit: Go from `cmap(110)` to `cmap(120)` (goes from dark red-orange to more vibrant orange)
    * First order fit: Go from `cmap(50)` to `cmap(169)` (goes from green to bright-ish yellow)

* It would be less confusing to use the same kind of line style for the "fit" plots, and a different one for the "analytic". That way the line style groups together what is fitted and analytic. (This does raise some problems if the fits are too similar.)

* Similarly, the colors associated with the zeroth order (first order) fit should be the same between the "fit" and "analytic" plots. That way it's possible to compare between the fit and analytic plots by color.

(Note: If the above suggestions don't jive with whatever scientific interpretations were suppose to draw from the data -- i.e., does it make sense to compare the "fit" and "analytic" parts of the plot for each other? -- then we should certainly change the suggestions!)

* When plotting the data, we could use the `zorder` parameter to put the data on top of everything else. (Setting it to some number, like 10, should ensure we plot the data above all the other lines.)

* Set the x-axis label by using the capitalized name of the gate:

```python
xlabel = 'RB Sequence Length ({0}s)'.format(gstyp.capitalize())
```

An example plot showing these suggestions is below, where I made up some numbers of `analytic_params`. (pdf downloads to your computer.)

[example.pdf](https://github.com/pyGSTio/pyGSTi/files/562793/example.pdf)

**Comment by tjproct** [comment]
These changes have now either been implemented as suggested, or I've instead done very similar changes to those suggested.
