### ISSUE TITLE
More consistent use of submembers of state/povm ModelMembers

### ISSUE THREAD

**Issue by sserita** [pyGSTio/pyGSTi#208]
**Is your feature request related to a problem? Please describe.**
Operations keep track of submembers really well but states/povms less so. This has caused us minor issues in the past, but is a bigger pain point now that we are trying to do model serialization.

**Describe the solution you'd like**
Referenced states/POVMs are listed in submembers of wrapping states/POVMs, even if with the static parameterization. This is consistent with how static op + noise ops are handled for ComposedOp, etc.

- [ ] ComposedState.state_vec
- [ ] TensorProductState.factors
- [ ] ComposedEffect.effect_vec
- [ ] ComposedPOVM.base_povm
- [ ] MarginalizedPOVM.povm_to_marginalize
- [ ] TensorProdPOVMEffect.factors
- [ ] TensorProdPOVM.factorPOVMS (this is also inconsistent style)

**Describe alternatives you've considered**
If these are not added as submembers, the model serialization routines will need to be hard-coded  for each of the instances listed above. MarginalizedPOVMs will need specialized code regardless, but the less, the better.

**Additional context**
Besides making serialization easier, this would also open up the possibility for non-static "wrapped" states/povms, providing greater flexibility.

**Comment by enielse** [comment]
I believe all of the POVMs and Instruments have been updated to use the "submembers" framework now, and this is included in the 0.9.10 release.
