### ISSUE TITLE
workspace object + exec() command

### ISSUE THREAD

**Issue by Travis-S** [pyGSTio/pyGSTi#23]
On the `feature-dashboards` branch in Tutorial 20, running this code

```python
from pygsti.report import workspace
w = workspace.Workspace()
```

Gave rise to this `SyntaxError`:

```python
File "/Users/tlschol/Desktop/pyGSTi/packages/pygsti/report/workspace.py", line 158
    exec(factory_func_def, exec_globals) #Python 3
SyntaxError: function 'makefactory' uses import * and bare exec, which are illegal because it is a nested function
```

In `pygsti/report/workspace.py`, the relevant lines are

```python
exec_globals = {'cls' : cls, 'self': self}
if _sys.version_info > (3, 0):
    exec(factory_func_def, exec_globals) #Python 3
else:
    exec("""exec factory_func_def in exec_globals""") #Python 2
```

A similar issue arises if you comment out the first part of the if/then, and have the interpreter check the other line:

```python
File "/Users/tlschol/Desktop/pyGSTi/packages/pygsti/report/workspace.py", line 161
    exec("""exec factory_func_def in exec_globals""") #Python 2
SyntaxError: unqualified exec is not allowed in function 'makefactory' because it is a nested function
```

This syntax error prevents the creation of the workspace object, which in turn blocks the user from executing any of the remaining code in Tutorials 20, 21, or 22.

The system I am using has pygsti 0.9.3, and Python 2.7.12 :: Anaconda custom (x86_64).

**Comment by enielse** [comment]
Thanks for noticing this Travis.  I had only been testing with Python3.  I think commit 1a98c84999087689454b7f13c937133f5b986356 to `feature-dashboards` fixes the issues with running the Tutorials.  Please try again and let me know if you still encounter issues.

**Comment by Travis-S** [comment]
The workspace object is now operating! The tutorials run.

**Comment by Travis-S** [comment]
Closing this issue.
