### ISSUE TITLE
BootstrappedErrorBars.ipynb Failure

### ISSUE THREAD

**Issue by warrench** [pyGSTio/pyGSTi#240]
**Describe the bug**
Generating analysis of parametric and non-parametric bootstrap model fails.

circuit labels in long sequence GST are not being generated and passed through bootstrap methods.

**To Reproduce**

Run notebook from fresh installation of pygsti following install instructions

**Expected behavior**

The notebook to run without error

**Environment (please complete the following information):**
 - pyGSTi  v0.9.10.1
 - python 3.10, 4
 - Windows10
[GSTerror.txt](https://github.com/pyGSTio/pyGSTi/files/8389692/GSTerror.txt)

**Comment by sserita** [comment]
Closed as this is now in 0.9.11 release
