### ISSUE TITLE
Generating 3Q Models breaks fiducial selection

### ISSUE THREAD

**Issue by warrench** [pyGSTio/pyGSTi#245]
**Describe the bug**
Extending to more than two qubits breaks the way that forwardsimulation is implemented in the model and other components of pyGSTi break because of this. Namely trying to generate a set of fiducial elements for a particular model using `find_fiducials(targ_model)`

In the 2Q instance the forward simulator for the model is `<class 'pygsti.forwardsims.matrixforwardsim.MatrixForwardSimulator'>`

Whereas for the 3Q instance the forward simulator for the model is `<class 'pygsti.forwardsims.mapforwardsim.MapForwardSimulator'>`

This causes the error in the find_fiducial function as the MapForwardSimulator does not have an attribute `product()`

**To Reproduce**
Run between the two generated models

`import pygsti as gst`

`target_model = gst.models.modelconstruction.create_explicit_model_from_expressions( `
          `                         [('Q0','Q1')],['Gii','Gix','Giy','Gxi','Gyi'], `
          `                         [ "I(Q0):I(Q1)", "X(pi/2,Q1)", "Y(pi/2,Q1)", "X(pi/2,Q0)", "Y(pi/2,Q0)" ])`

`# target_model = gst.models.modelconstruction.create_explicit_model_from_expressions( `
`#             [('Q0','Q1','Q2')],`
`#             ['Giii','Giix','Giiy','Gixi','Giyi','Gxii','Gyii'], `
`#             [ "I(Q0):I(Q1):I(Q2)", "X(pi/2,Q2)", "Y(pi/2,Q2)", "X(pi/2,Q1)", "Y(pi/2,Q1)", "X(pi/2,Q0)", "Y(pi/2,Q0)" ])`

`prepFid, measFid = gst.algorithms.fiducialselection.find_fiducials(target_model)`

**Expected behavior**
Should be able to run the find_fiducial algorithm

**Environment (please complete the following information):**
 - pyGSTi  v0.9.10.1
 - python 3.10.4

**Comment by warrench** [comment]
Error File
[GSTerror.txt](https://github.com/pyGSTio/pyGSTi/files/8710137/GSTerror.txt)

**Comment by warrench** [comment]
Hi thank you for the quick response.

This does indeed fix the issue and `find_fiducial()` does run now for 3Q. 

I guess a separate issue not related to this is that `find_fiducial()` does not find prep or measurement fiducials for the 3Q case above after running with GRASP. This is a separate issue, but perhaps I need to investigate the options of `find_fiducial()` a bit more. I also noticed that running it on the 2Q case above also has issues finding preparation fiducials, but does converge and find measurement fiducials.

**Comment by sserita** [comment]
Yes, there are quite a few options for fiducial/germ selection to play with. The best place to start would be the fid/germ selection [tutorial](https://github.com/pyGSTio/pyGSTi/blob/master/jupyter_notebooks/Tutorials/algorithms/advanced/GST-FiducialAndGermSelection.ipynb).

As for the 2Q model, I'll note that what you have is the same as the smq2Q_XXYYII modelpack, so you could look to see what fids/germs we have stored in there.

**Comment by warrench** [comment]
Including pi and -pi/2 pulses is actually more representative of my true setup so I will give that suggestion a shot

**Comment by sserita** [comment]
I think we'd be happy to have a call and talk about how to generate a reasonable GST design. Often knowing a little about the pecularities/physics goes a long way in setting those arguments.

Feel free to email sserita@sandia.gov and enielse@sandia.gov - a lot of the PyGSTi dev team is at a meeting this week, but we can try to set something up for next week or so.

**Comment by sserita** [comment]
This should be a lot more doable as of PR #270. Leaving the issue open until these changes are in an official release, though.

**Comment by sserita** [comment]
Closed as this is now in 0.9.11 release
