### ISSUE TITLE
Calculating negative eigenvalues of the choi matrix

### ISSUE THREAD

**Issue by dcmckay** [pyGSTio/pyGSTi#25]
If I use the different functions in jamiolkowski.py to calculate the negative e-vals I get inconsistent values. I think the problem is that `mags_of_negative_choi_evals()` does not call `jamiolkowski_iso()` with the basis of the gates in the gateset.

**Comment by enielse** [comment]
This was a confirmed bug - thanks for alerting us to it!  It has been fixed as of pyGSTi 0.9.4
