### ISSUE TITLE
IOError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by wuchichou** [pyGSTio/pyGSTi#3]
It occurred when I run the tutorial file `00 Quick and easy GST.ipynb` and `07 Report Generation.ipynb`. The error is same in both files. When it read the `.create_presentation_ppt`, it can't find `progressTable.png` file.
Here is the traceback:
```
IOError                                   Traceback (most recent call last)
<ipython-input-14-dac62d848da6> in <module>()
      1 #create GST slides (tables and figures of full report in Powerpoint slides; best for folks familiar with GST)
----> 2 results.create_presentation_ppt(confidenceLevel=95, filename="tutorial_files/easy_slides.pptx", verbosity=2)

/home/wujizhou/pyGSTi/packages/pygsti/report/results.py in create_presentation_ppt(self, confidenceLevel, filename, title, datasetLabel, suffix, debugAidsAppendix, pixelPlotAppendix, whackamoleAppendix, m, M, verbosity, pptTables)
   2338             #body_shape = slide.shapes.placeholders[1]; tf = body_shape.text_frame
   2339             add_text_list(slide.shapes, 1, 2, 8, 2, ['Ns is the number of gate strings', 'Np is the number of parameters'], 15)
-> 2340             drawTable(slide.shapes, 'progressTable', 1, 3, 8.5, 4, ptSize=10)
   2341 
   2342             slide = add_slide(SLD_LAYOUT_TITLE_NO_CONTENT, "Detailed %s Analysis" % plotFnName)

/home/wujizhou/pyGSTi/packages/pygsti/report/results.py in draw_table_latex(shapes, key, left, top, width, height, ptSize)
   2279 
   2280             pathToImg = _os.path.join(fileDir, "%s.png" % key)
-> 2281             return draw_pic(shapes, pathToImg, left, top, width, height)
   2282 
   2283 

/home/wujizhou/pyGSTi/packages/pygsti/report/results.py in draw_pic(shapes, path, left, top, width, height)
   2283 
   2284         def draw_pic(shapes, path, left, top, width, height):
-> 2285             pxWidth, pxHeight = Image.open(open(path)).size
   2286             pxAspect = pxWidth / float(pxHeight) #aspect ratio of image
   2287             maxAspect = width / float(height) #aspect ratio of "max" box

IOError: [Errno 2] No such file or directory: 'tutorial_files/easy_slides_files/progressTable.png'
```

**Comment by enielse** [comment]
By default pyGSTi generated figures and tables for PowerPoint presentations by rendering "standalone" latex files with pdflatex.  That progressTable.png is missing indicates that there was some problem with this rendering that wasn't caught as reported as such.  Please try to compile the attached [standalone.tex](https://github.com/pyGSTio/pyGSTi/files/192206/standalone.tex.zip) file (the template file used by pyGSTi) via:

`pdflatex standalone.tex`

I expect this will result in pdflatex giving you some meaningful error which you can fix.  If this is the case, please post what error your were getting so we can add a fix to handle it gracefully in the future.

**Comment by wuchichou** [comment]
@enielse thank you for giving me the right direction to figure out what's wrong with my problem. I find the error occurs because it can't find `convert`. After installing the imagemagick, it works well.
