### ISSUE TITLE
Fix/Update Read The Docs

### ISSUE THREAD

**Issue by coreyostrove** [pyGSTio/pyGSTi#307]
Read the docs is currently not being rebuilt on their servers do to some compile issue the devs over there alerted us to a while back. We should get this fixed so that they are recompiled to match the current docstrings appropriately.

More broadly there are a number of aesthetic changes I would like to make to the documentation, bringing them closer to the previous navigation style, so I would like to fold these changes in at the same time. 

We've also run into compute time limit issues with the read the docs servers in the past so we should reach out and request an extra time allotment for builds.

**Comment by sserita** [comment]
Being updated at least by #331

**Comment by sserita** [comment]
Closing with the release of 0.9.11.2
