### ISSUE TITLE
Per-germ global FPR

### ISSUE THREAD

**Issue by coreyostrove** [pyGSTio/pyGSTi#308]
We have an implementation of a new form of FPR that leverages global information about the properties of a germ set to further streamline the costs of an experiment design. This currently lives on the branch feature-globally-germ-aware-FPR and is nearly ready to be merged into develop in anticipation of the next release. Still left to-do:

- Build out unit tests
- Update the fiducial pair reduction example notebook to reflect new functionality

**Comment by sserita** [comment]
Completed with the merge of #350.

**Comment by sserita** [comment]
Closed with release of 0.9.12.
