### ISSUE TITLE
Update python versions for pre-built wheels

### ISSUE THREAD

**Issue by coreyostrove** [pyGSTio/pyGSTi#309]
Not exactly a bug, but I noticed while browsing pypi that we don't currently have pre-built wheels appearing for python 3.10. Since we've added official support for 3.10 with the latest release we should update the relevant CI workflow to make sure those wheels get built. It might also be worth debating whether or not to continue including pre-built wheels for python 3.6 on pypi now that we have dropped official support. Thoughts?

**Comment by sserita** [comment]
Closing with the release of 0.9.11.2
