### ISSUE TITLE
write_empty_protocol_data doesn't work with non-standard POVMs

### ISSUE THREAD

**Issue by coreyostrove** [pyGSTio/pyGSTi#321]
When using the function `pygsti.io.write_empty_protocol_data` the resulting template dataset looks to be hardcoded for standard computational basis readout. As such, when working with models that have non-standard/default POVMs, either ones with different measurement effects altogether we get the incorrect effect labels written into the template dataset file.

The expected behavior here would be to introspect the experiment design for its model/processor spec and to then base the dataset labels based on the corresponding POVM's labels. To _really_ do this right we probably need to also need to check for whether there are multiple POVMs with incommensurate effect labels and add logic for managing these if so.

**Comment by sserita** [comment]
Closed with release of 0.9.12.
