### ISSUE TITLE
DataSet Pickling Bug

### ISSUE THREAD

**Issue by coreyostrove** [pyGSTio/pyGSTi#322]
With the addition of MongoDB serialization functionality it looks like the pickling routines for `DataSet` objects, which have custom `__get_state__` and `__set_state__` methods, are out of sync. Specifically I ran into an issue when using MPI for some GST runs where the `_dbcoordinates` attribute from the `MongoSerializable` parent class got dropped after unpickling which causes problems in `pygsti.io.write_dataset` which is expecting this attribute to be there. mpi4py uses pickle under the hood for communication of python objects between ranks which is how I ran into this.

Attached is a minimalish working example (you should be able to reproduce this just as well using pickle directly, but since I ran into this with MPI it was more convenient to make an example in that context). 

I've temporarily patched this on feature-globally-germ-aware-fpr by adding the `_dbcoordinates` attribute to the DataSet state dict, but I'm not sure if that is the correct solution in general for this sort of thing.

[dataset_pickle_bug_example.zip](https://github.com/pyGSTio/pyGSTi/files/11618453/dataset_pickle_bug_example.zip)

**Comment by sserita** [comment]
Closing with the release of 0.9.11.2
