### ISSUE TITLE
Deprecated code in "Getting Started" in README

### ISSUE THREAD

**Issue by nemill** [pyGSTio/pyGSTi#325]
**Describe the bug**
In the "Getting Started" section of the README.md file, both examples contain:
from pygsti.construction import std1Q_XYI

pygsti.construction appears to be deprecated, possibly replaced by pygsti.modelpacks

**To Reproduce**
Running the line above produces:
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[8], line 1
----> 1 from pygsti.construction import std1Q_XYI

ModuleNotFoundError: No module named 'pygsti.construction'

**Expected behavior**
The Getting Started section promises some quick examples of circuit simulation and gate set tomography, both of which are dependent on this deprecated package. It would be helpful to update this "Getting Started" section with the most current packages/syntax, possibly pointing to the tutorials.

**Environment (please complete the following information):**
 - pyGSTi version 0.9.11.1
 - python version 3.10.9
 - OS - Windows 11

**Comment by sserita** [comment]
This is now fixed in `bugfix-example-updates` as of commit `79a16ad`. That branch will likely stay open for things in issue #317 for now, though.

**Comment by sserita** [comment]
Closed with release of 0.9.12.
