### ISSUE TITLE
Several functions have mutable default arguments

### ISSUE THREAD

**Issue by rileyjmurray** [pyGSTio/pyGSTi#355]
I came across a function in pygsti version 0.9.11.2 that has a mutable default argument. This can lead to nasty bugs, as described [here](https://docs.python-guide.org/writing/gotchas/). Once I found the first bug of this kind, I ran some searches and found several more. See below for a list.

#### Search results

I ran a regex search for strings of the form ``=[]<characters here>):`` [1] and found the following hits:
![image](https://github.com/pyGSTio/pyGSTi/assets/10662932/12eead34-ed88-4c16-ae16-a32ae0c11643)

If I search for strings of the form ``={}<characters here>):`` [2], I get 
![image](https://github.com/pyGSTio/pyGSTi/assets/10662932/e4115220-526b-43ab-9806-e33d5fa6d97f)

#### Footnotes

[Footnote 1] ``<insert characters here>`` is a placeholder for any character sequence that excludes new lines. The actual regex I used was ``=\[\].+\):``. Note that this doesn't capture all possible cases where we have mutable default arguments, since it will miss cases of multi-line function definitions where the mutable argument isn't on the last line.

[Footnote 2] The actual regex I used was ``=\{\}.+\):``.

You can search for both patterns I checked with ``=[\{\[][\}\]].+\):``.

**Comment by sserita** [comment]
Closed with release of 0.9.12.
