### ISSUE TITLE
Python Version Deprecations for 0.9.12

### ISSUE THREAD

**Issue by coreyostrove** [pyGSTio/pyGSTi#356]
Python 3.12.0 came out earlier this month which put version support back on my mind. With 0.9.12 coming down the pipeline soon it would be a good opportunity to officially announce a deprecation of official support for python 3.7 with the intention of removing it from our CI testing pipeline in 0.9.13. Ideally we'd also target 0.9.13 for adding in official python 3.11 support at the same time (we already have a number of users on this version of python and have done some patches related to this so it probably wouldn't be too much of a lift).

Thoughts?

**Comment by sserita** [comment]
Completely agree - let's plan to deprecate 3.7 in release 0.9.12, and then drop 3.7 and add 3.11 for release 0.9.13. I think at this point we've got many of the main bugs with 3.11, but I'm sure the tests will catch a few more.

Is there an easy way to indicate python version deprecation? Maybe @rileyjmurray knows this? In the past, I think we have just dropped and added Python version support with no warning, but we can always strive to do better.

**Comment by rileyjmurray** [comment]
With CVXPY, our policy is that we can drop support for a version of Python without warning _if_ the Python Software Foundation drops support for that version. Since the PSF dropped support for 3.7 a while back I'd say there's good cause to drop it from pyGSTi's supported Python versions.

**Comment by sserita** [comment]
Closed with release of 0.9.12.
