### ISSUE TITLE
Have pyGSTi check qibo version before attempting to execute qibo functions

### ISSUE THREAD

**Issue by rileyjmurray** [pyGSTio/pyGSTi#363]
PyGSTi can optionally use a Python package called "qibo" for one of its evotypes ([see here](https://github.com/pyGSTio/pyGSTi/tree/master/pygsti/evotypes/qibo)).

At time of writing, pyGSTi isn't compatible with qibo version 0.2.x or higher. If you install pygsti with ``pip install -e .['testing']`` then you should get qibo 0.1.7 and pyGSTi works normally. 

Here's the problem. If you somehow get qibo version 0.2.x in the same Python environment as pyGSTi, then pyGSTi will assume it's the older version. This can lead to uninformative errors and/or crashes. We should update pyGSTi's relevant qibo code to do runtime check(s) that an acceptable version of qibo is installed.

**Comment by sserita** [comment]
This is also related to #262. Short-term we will make sure all versions are pinned to 0.1.7, long-term we will deprecate and remove Qibo. It is not what we are looking for in a third-party integrated simulator and has seen no use.
