### ISSUE TITLE
Colon in filename of example notebooks creates problem on Windows

### ISSUE THREAD

**Issue by AdriaanRol** [pyGSTio/pyGSTi#38]
@enielse 

Hi Erik, 
I recently tried updating to the latest version of the beta branch of pyGSTi. Whenever I try to check out the latest version I run into the problem that some example notebooks are not present (see screenshot below). This is flagged as file deletions by git. 

It appears that the problem is because windows does not allow colons (`:`) in filenames. A simple solution would be to rename the offending notebooks. 

![image](https://user-images.githubusercontent.com/6142932/41920891-ef3a2a82-7961-11e8-94aa-243132ba1eff.png)

**Comment by enielse** [comment]
Thanks for pointing this out.  We actually discovered this independently a just few weeks ago.  The colons have been removed from all filenames on the develop branches now, and so they'll be fixed on the master branch at the next release (which will be 0.9.5), which we're aiming for a 1-2 weeks from now.  Let's leave this issue open until that happens.

**Comment by enielse** [comment]
Well... 1-2 weeks turned into 1-2 months, but version 0.9.5 is just out, and has the colon-free filenames .
