### ISSUE TITLE
Dataset serialization is python version-dependent (low priority)

### ISSUE THREAD

**Issue by robpkelly** [pyGSTio/pyGSTi#46]
See https://travis-ci.org/pyGSTio/pyGSTi/jobs/505328727, for instance

Pickling datasets in python 3.7 includes `uuid.SafeUUID`, which isn't present in earlier python versions. A dataset saved in 3.7 can't be opened in 3.5 or 2.7.

We should serialize datasets some other way, probably using numpy's builtin serialization.

**Comment by robpkelly** [comment]
patched in 0d185fcd0f, will leave this open until we have a long-term solution

**Comment by enielse** [comment]
This and other pickle serialization issues should be fixed in version 0.9.10, which includes support for serializing many pygsti objects to JSON files rather than relying on pickle.  Data sets should be written in their text format for long term storage.
