### ISSUE TITLE
Migrate to travis-ci.com (low priority)

### ISSUE THREAD

**Issue by robpkelly** [pyGSTio/pyGSTi#47]
As of May 2018, Travis CI has been restructuring their handling of open-source projects. Projects on `travis-ci.org` are being migrated to `travis-ci.com`. See https://docs.travis-ci.com/user/migrate/open-source-on-travis-ci-com/

We should opt-in to migrate ours. We'd get some nice features like deploy keys. Should be mostly painless -- I think the only thing we'll need to update is the build badge URL in the README. We may temporarily lose build history, but I think that should still be accessible through `travis-ci.org`

**Comment by sserita** [comment]
@enielse Bump on this issue. `travis-ci.org` will be going read-only on Dec 31 2020: https://docs.travis-ci.com/user/migrate/open-source-repository-migration#q-what-will-happen-to-travis-ciorg-after-december-31st-2020

**Comment by sserita** [comment]
Closed with migration to GitHub Actions
