### ISSUE TITLE
Cannot import" idletomography"

### ISSUE THREAD

**Issue by enielse** [pyGSTio/pyGSTi#68]
After installing via pip, importing `pygsti.extras.idletomography` fails with an error something like:
`ImportError: cannot import name 'idletomography' from 'pygsti.extras'`

In particular, this bug will surface when trying to generate HTML reports.  This is due to a bug in setup.py that omits the idletomography package when copying files during pip's install process.

**Comment by robpkelly** [comment]
Fixed with [hotfix v0.9.7.5](https://github.com/pyGSTio/pyGSTi/releases/tag/v0.9.7.5). Thanks for the heads-up!
