### ISSUE TITLE
Automated testing for notebooks

### ISSUE THREAD

**Issue by robpkelly** [pyGSTio/pyGSTi#92]
Obviously we need to be checking that patches aren't breaking the tutorial/example notebooks. Programmatic execution of notebooks looks pretty straightforward so we can just whip up a quick script to smoke-test our notebooks in CI.

**Comment by robpkelly** [comment]
Maybe useful? https://github.com/taavi/ipython_nose

**Comment by robpkelly** [comment]
Clearing out old issues... We've already got a test module for notebooks, so we just ought to run it from CI

**Comment by coreyostrove** [comment]
Automated notebook regression testing via the nbval module for pytest has been added with PR #300.

**Comment by sserita** [comment]
Closed as this is now in 0.9.11 release
